# main process config
main:
  root_dir: "IP"
  function_name: "foo"
  debug: true
  only_loop: false
  recursive_loop: false
  auto_annotation: true
  refine_count: 0
  pass_count: 1
  think: false
  template: false
  auto_post: false
  use_db: false
  collect: false

# LLM Config
llm:
  api_model: "gpt-4o"

# precondition config
preconditions:
  foo: "emp"
