# main process config
main:
  root_dir: "motivation_example"
  function_name: "foo"
  debug: true
  only_loop: true
  recursive_loop: false
  auto_annotation: true
  refine_count: 3
  pass_count: 5
  think: true
  template: true
  auto_post: true
  use_db: false
  collect: false

# LLM Config
llm:
  api_model: "gpt-4o"

# precondition config
preconditions:
  foo: "emp"
